import assert from 'node:assert/strict';
import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import {spawnSync} from 'node:child_process'; import test from 'node:test';
const root=path.resolve(import.meta.dirname,'..'), helper=path.join(root,'scripts/dev-v4-admission.mjs');
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'impactshop-v4-'));spawnSync('/usr/bin/git',['-C',dir,'init','-q']);spawnSync('/usr/bin/git',['-C',dir,'config','user.email','fixture@example.invalid']);spawnSync('/usr/bin/git',['-C',dir,'config','user.name','Fixture']);fs.writeFileSync(path.join(dir,'README'),'fixture');spawnSync('/usr/bin/git',['-C',dir,'add','.']);spawnSync('/usr/bin/git',['-C',dir,'commit','-qm','fixture']);return dir}
function mergedFixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'impactshop-v4-fresh-'));const clone=spawnSync('/usr/bin/git',['clone','--shared','-q',root,dir],{encoding:'utf8'});assert.equal(clone.status,0);spawnSync('/usr/bin/git',['-C',dir,'checkout','-q','c401a9709027a9d7e14bc7e91f0478d094205af']);spawnSync('/usr/bin/git',['-C',dir,'switch','-q','-c','feat/fresh-launcher-fixture']);spawnSync('/usr/bin/git',['-C',dir,'update-ref','refs/remotes/origin/main','c401a9709027a9d7e14bc7e91f0478d094205af']);const head=spawnSync('/usr/bin/git',['-C',dir,'rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim(),tree=spawnSync('/usr/bin/git',['-C',dir,'show','-s','--format=%T','HEAD'],{encoding:'utf8'}).stdout.trim(),marker=path.join(dir,'.git','worktree-active.json');fs.writeFileSync(marker,JSON.stringify({schema_version:2,path:fs.realpathSync(dir),base:{ref:'origin/main',commit:head},current:{head,tree,branch:'feat/fresh-launcher-fixture'},selector:'maintenance-docs'}));fs.chmodSync(marker,0o600);return dir}
test('markerless pre-merge candidate is explicitly v2-only without writes',()=>{const dir=fixture();try{const r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'});assert.equal(r.status,0);const p=JSON.parse(r.stdout);assert.equal(p.v4.state,'v2-only');assert.equal(p.combinedDecision,'planning-only');}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('unsafe nonlegacy capsule is blocked in a temporary fixture',()=>{const dir=fixture();try{const marker=path.join(dir,'.git','worktree-active.json'),target=path.join(dir,'unsafe');fs.writeFileSync(target,'x');fs.symlinkSync(target,marker);const r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'});assert.equal(r.status,0);assert.equal(JSON.parse(r.stdout).combinedDecision,'blocked');}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('corrected central snapshot and atomic marker contract are pinned',()=>{
  const snapshot=JSON.parse(fs.readFileSync(path.join(root,'config/dev-v4/central-contract-snapshot.v2.json')));
  assert.equal(snapshot.centralMergeSha,'94db78c66b21979c9511594344649a518a4d31d8');
  assert.equal(snapshot.centralTree,'6fd0f87b40b74e74abce72caf03a48280f7659ab');
  assert.equal(snapshot.supersedes,'config/dev-v4/central-contract-snapshot.v1.json');
  assert.equal(snapshot.supersededSnapshotSha256,'935482cf99e122e872126520f7f17d24c6dc01cb35212c66cda511cba79073e9');
  const starter=fs.readFileSync(path.join(root,'scripts/worktree-task-start.sh'),'utf8');
  assert.match(starter,/fchmod\(fd, 0o600\)/); assert.match(starter,/os\.replace\(temp, marker_file\)/);
});
test('an unmerged feature HEAD cannot self-claim origin/main authority',()=>{const dir=fixture();try{const realDir=fs.realpathSync(dir),base=spawnSync('/usr/bin/git',['-C',dir,'rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim();spawnSync('/usr/bin/git',['-C',dir,'update-ref','refs/remotes/origin/main',base]);fs.appendFileSync(path.join(dir,'README'),'\ncandidate');spawnSync('/usr/bin/git',['-C',dir,'add','README']);spawnSync('/usr/bin/git',['-C',dir,'commit','-qm','candidate']);const head=spawnSync('/usr/bin/git',['-C',dir,'rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim(),tree=spawnSync('/usr/bin/git',['-C',dir,'show','-s','--format=%T','HEAD'],{encoding:'utf8'}).stdout.trim(),branch=spawnSync('/usr/bin/git',['-C',dir,'branch','--show-current'],{encoding:'utf8'}).stdout.trim(),marker=path.join(dir,'.git','worktree-active.json');fs.writeFileSync(marker,JSON.stringify({schema_version:2,path:realDir,base:{ref:'origin/main',commit:head},current:{head,tree,branch},selector:'protected-source',plan_id:'fixture-plan'}));fs.chmodSync(marker,0o600);const r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'}),p=JSON.parse(r.stdout);assert.equal(p.v4.state,'v2-only');assert.deepEqual(p.v4.reasons,['stage_b_base_not_on_mainline']);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('true fresh launcher context-pack artifact is admitted',()=>{const dir=mergedFixture();try{fs.mkdirSync(path.join(dir,'.codex','context'),{recursive:true});fs.writeFileSync(path.join(dir,'.codex','context','feat-fresh-launcher-fixture.md'),'private context');const r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'}),p=JSON.parse(r.stdout);assert.equal(p.v4.state,'implementation-ready');}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('private context boundary does not admit other codex files',()=>{const dir=mergedFixture();try{fs.mkdirSync(path.join(dir,'.codex'),{recursive:true});fs.writeFileSync(path.join(dir,'.codex','unexpected.md'),'not generated context');const r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'}),p=JSON.parse(r.stdout);assert.equal(p.v4.state,'blocked');assert.deepEqual(p.v4.outsidePaths,['.codex/unexpected.md']);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
