import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { evaluatePhpCapability, validatePhpBinary, validatePhpObservation, validatePhpReceipt } from '../scripts/dev-v4-admission.mjs';
import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import {spawnSync} from 'node:child_process'; import test from 'node:test';
const root=path.resolve(import.meta.dirname,'..'), helper=path.join(root,'scripts/dev-v4-admission.mjs');
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'impactshop-v4-'));spawnSync('/usr/bin/git',['-C',dir,'init','-q']);spawnSync('/usr/bin/git',['-C',dir,'config','user.email','fixture@example.invalid']);spawnSync('/usr/bin/git',['-C',dir,'config','user.name','Fixture']);fs.writeFileSync(path.join(dir,'README'),'fixture');spawnSync('/usr/bin/git',['-C',dir,'add','.']);spawnSync('/usr/bin/git',['-C',dir,'commit','-qm','fixture']);return dir}
function mergedFixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'impactshop-v4-fresh-'));const clone=spawnSync('/usr/bin/git',['clone','--shared','-q',root,dir],{encoding:'utf8'});assert.equal(clone.status,0);spawnSync('/usr/bin/git',['-C',dir,'checkout','-q','c401a9709027a9d7e14bc7e91f0478d094205af']);spawnSync('/usr/bin/git',['-C',dir,'switch','-q','-c','feat/fresh-launcher-fixture']);spawnSync('/usr/bin/git',['-C',dir,'update-ref','refs/remotes/origin/main','c401a9709027a9d7e14bc7e91f0478d094205af']);const head=spawnSync('/usr/bin/git',['-C',dir,'rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim(),tree=spawnSync('/usr/bin/git',['-C',dir,'show','-s','--format=%T','HEAD'],{encoding:'utf8'}).stdout.trim(),marker=path.join(dir,'.git','worktree-active.json');fs.writeFileSync(marker,JSON.stringify({schema_version:2,repo:'impactshop-notes',path:fs.realpathSync(dir),branch:'feat/fresh-launcher-fixture',base:{ref:'origin/main',commit:head},current:{head,tree},selector:'maintenance-docs'}));fs.chmodSync(marker,0o600);return dir}
test('markerless pre-merge candidate is explicitly v2-only without writes',()=>{const dir=fixture();try{const r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'});assert.equal(r.status,0);const p=JSON.parse(r.stdout);assert.equal(p.v4.state,'v2-only');assert.equal(p.combinedDecision,'planning-only');}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('unsafe nonlegacy capsule is blocked in a temporary fixture',()=>{const dir=fixture();try{const marker=path.join(dir,'.git','worktree-active.json'),target=path.join(dir,'unsafe');fs.writeFileSync(target,'x');fs.symlinkSync(target,marker);const r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'});assert.equal(r.status,0);assert.equal(JSON.parse(r.stdout).combinedDecision,'blocked');}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('corrected central snapshot and atomic marker contract are pinned',()=>{
  const snapshot=JSON.parse(fs.readFileSync(path.join(root,'config/dev-v4/central-contract-snapshot.v2.json')));
  assert.equal(snapshot.centralMergeSha,'94db78c66b21979c9511594344649a518a4d31d8');
  assert.equal(snapshot.centralTree,'6fd0f87b40b74e74abce72caf03a48280f7659ab');
  assert.equal(snapshot.supersedes,'config/dev-v4/central-contract-snapshot.v1.json');
  assert.equal(snapshot.supersededSnapshotSha256,'935482cf99e122e872126520f7f17d24c6dc01cb35212c66cda511cba79073e9');
  const starter=fs.readFileSync(path.join(root,'scripts/worktree-task-start.sh'),'utf8');
  assert.match(starter,/fchmod\(fd, 0o600\)/); assert.match(starter,/os\.replace\(temp, marker_file\)/); assert.match(starter,/"current": \{"head": base_sha, "tree": base_tree, "recorded_at": started_at\}/);
});

test('future S4/S5 selectors are exact and require PHP plus existing test capabilities',()=>{const policy=JSON.parse(fs.readFileSync(path.join(root,'config/dev-v4/stage-b-activation-policy.v1.json'))),common=['docs/impactshop-protected-files.json','docs/impactshop-guard-config.json','docs/impactshop-guard-hashes.json','docs/impactshop-guard-hashes.sha256','docs/bastion-guard-status.md','docs/impactshop-governance-system-plan-2026-06-16.md','docs/impactshop-notes-doc-sync-map-2026-06-23.md'];const expected={
  'sharity-ngo-preference-s4-profile-consumer':['wp-content/mu-plugins/000-impactshop-owner-policy.php','wp-content/mu-plugins/impactshop-identity-panel.php','wp-content/mu-plugins/impactshop-identity-panel.js','tests/impactshop-identity-profile-v2-static.test.py','tests/impactshop-profile-route-path.test.php','tests/impactshop-owner-policy-inventory.test.py','scripts/impactshop-owner-policy-inventory.php',...common,'docs/sharity-profile-summary-live-closure-luna-continuity-20260910.md','docs/sharity-ngo-preference-v4-4-s4-profile-consumer-2026-09-13.md','docs/protected-change-records/2026-09-13-sharity-ngo-preference-v4-4-s4-profile-consumer.md','docs/continuity/dev/2026-09-13-sharity-ngo-preference-v4-4-s4-profile-consumer.md','notes.md','system-status-snapshot.md'],
  'sharity-ngo-preference-s5-provider-activity-adapter':['wp-content/mu-plugins/impactshop-sharity-activity-receipt.php','tests/sharity-affiliate-runtime-bastion.test.sh','scripts/sharity-affiliate-runtime-bastion-guard.sh','tests/impactshop-sharity-activity-receipt.test.php','tests/impactshop-sharity-activity-receipt-static.test.py',...common,'docs/sharity-ngo-preference-v4-4-s5-provider-activity-adapter-2026-09-13.md','docs/protected-change-records/2026-09-13-sharity-ngo-preference-v4-4-s5-provider-activity-adapter.md','docs/continuity/dev/2026-09-13-sharity-ngo-preference-v4-4-s5-provider-activity-adapter.md','notes.md','system-status-snapshot.md']
};for(const [id,paths] of Object.entries(expected)){const rule=policy.selectors[id];assert.equal(rule.lane,'protected');assert.equal(rule.requiresPlanId,true);assert.deepEqual(rule.requiredCapabilities,['php-runtime','git-readback','static-node-test']);assert.deepEqual(rule.writeSurface,paths);assert.ok(!rule.writeSurface.some(p=>p==='wp-content/'||p==='docs/'||p==='scripts/'||p==='tests/'||p.includes('*')))}});
test('original selectors remain unchanged',()=>{const policy=JSON.parse(fs.readFileSync(path.join(root,'config/dev-v4/stage-b-activation-policy.v1.json')));assert.deepEqual(policy.selectors['maintenance-docs'],{lane:'maintenance',riskCeiling:'low',requiresPlanId:false,writeSurface:['docs/','notes.md','system-status-snapshot.md']});assert.deepEqual(policy.selectors['standard-source'],{lane:'standard',riskCeiling:'medium',requiresPlanId:true,writeSurface:['AGENTS.md','.github/','config/','scripts/','tests/','docs/','notes.md','system-status-snapshot.md']})});
test('base-owned capability surface includes both admission control scripts',()=>{const capabilities=JSON.parse(fs.readFileSync(path.join(root,'config/dev-v4/repo-capabilities.v2.json'))),surface=capabilities.semanticSurfaces.find(item=>item.id==='dev-v4-stage-b');assert.deepEqual(surface.paths,['config/dev-v4/','scripts/dev-v4-admission.mjs','scripts/worktree-task-start.sh','tests/dev-v4-admission.test.mjs']);assert.equal(surface.authority,'base-owned')});
test('PHP capability is base-owned, scoped, and ignores candidate self-attestation',()=>{const base=spawnSync('/usr/bin/git',['-C',root,'rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim();const good=evaluatePhpCapability({base,selector:'s4',candidateReceipt:{state:'available'},phpPath:'/tmp/candidate'});if(good.state==='available'){assert.equal(good.evidence.authority,'base-owned');assert.equal(new Date(good.evidence.expiresAt)-new Date(good.evidence.observedAt),900000);}else assert.match(good.reason,/php_/);});
test('an unmerged feature HEAD cannot self-claim origin/main authority',()=>{const dir=fixture();try{const realDir=fs.realpathSync(dir),base=spawnSync('/usr/bin/git',['-C',dir,'rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim();spawnSync('/usr/bin/git',['-C',dir,'update-ref','refs/remotes/origin/main',base]);fs.appendFileSync(path.join(dir,'README'),'\ncandidate');spawnSync('/usr/bin/git',['-C',dir,'add','README']);spawnSync('/usr/bin/git',['-C',dir,'commit','-qm','candidate']);const head=spawnSync('/usr/bin/git',['-C',dir,'rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim(),tree=spawnSync('/usr/bin/git',['-C',dir,'show','-s','--format=%T','HEAD'],{encoding:'utf8'}).stdout.trim(),branch=spawnSync('/usr/bin/git',['-C',dir,'branch','--show-current'],{encoding:'utf8'}).stdout.trim(),marker=path.join(dir,'.git','worktree-active.json');fs.writeFileSync(marker,JSON.stringify({schema_version:2,repo:'impactshop-notes',path:realDir,branch,base:{ref:'origin/main',commit:head},current:{head,tree},selector:'protected-source',plan_id:'fixture-plan'}));fs.chmodSync(marker,0o600);const r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'}),p=JSON.parse(r.stdout);assert.equal(p.v4.state,'v2-only');assert.deepEqual(p.v4.reasons,['stage_b_base_not_on_mainline']);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('true fresh launcher context-pack artifact is admitted',()=>{const dir=mergedFixture();try{fs.mkdirSync(path.join(dir,'.codex','context'),{recursive:true});fs.writeFileSync(path.join(dir,'.codex','context','feat-fresh-launcher-fixture.md'),'private context');const r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'}),p=JSON.parse(r.stdout);assert.equal(p.v4.state,'implementation-ready');}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('private context boundary does not admit other codex files',()=>{const dir=mergedFixture();try{fs.mkdirSync(path.join(dir,'.codex'),{recursive:true});fs.writeFileSync(path.join(dir,'.codex','unexpected.md'),'not generated context');const r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'}),p=JSON.parse(r.stdout);assert.equal(p.v4.state,'blocked');assert.deepEqual(p.v4.outsidePaths,['.codex/unexpected.md']);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('candidate-modified admission self-blocks on active control drift',()=>{const dir=mergedFixture();try{fs.appendFileSync(path.join(dir,'scripts/dev-v4-admission.mjs'),'\n// candidate drift');const r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'}),p=JSON.parse(r.stdout);assert.equal(p.v4.state,'blocked');assert.deepEqual(p.v4.reasons,['active_control_object_drift']);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('candidate-modified task starter also self-blocks',()=>{const dir=mergedFixture();try{fs.appendFileSync(path.join(dir,'scripts/worktree-task-start.sh'),'\n# candidate drift');const r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'}),p=JSON.parse(r.stdout);assert.equal(p.v4.state,'blocked');assert.deepEqual(p.v4.reasons,['active_control_object_drift']);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('capsule rejects top-level repo or branch mismatch',()=>{const dir=mergedFixture();try{const marker=path.join(dir,'.git','worktree-active.json'),v=JSON.parse(fs.readFileSync(marker));v.repo='foreign-repo';fs.writeFileSync(marker,JSON.stringify(v));let r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'}),p=JSON.parse(r.stdout);assert.equal(p.v4.state,'blocked');v.repo='impactshop-notes';v.branch='foreign-branch';fs.writeFileSync(marker,JSON.stringify(v));r=spawnSync(process.execPath,[helper,'--phase0'],{cwd:dir,encoding:'utf8'});p=JSON.parse(r.stdout);assert.equal(p.v4.state,'blocked');}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('PHP evaluator rejects unsafe receipt and binary seams',()=>{assert.equal(validatePhpBinary('/tmp/php','/tmp/php',{isFile:true,isExecutable:true,mode:0o755}).ok,false);assert.equal(validatePhpBinary('/usr/bin/php','/usr/bin/php',{isFile:true,isExecutable:true,mode:0o775}).ok,false);const base=spawnSync('/usr/bin/git',['-C',root,'rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim();assert.equal(validatePhpReceipt({authority:'base-owned',provenance:'host-receipt',baseCommit:base,baseTree:'0'.repeat(40),selector:'x',subjectDigest:'x',validitySeconds:900,lint:'pass',fixture:'pass',observedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+900000).toISOString()},base,'x'),false)});
test('PHP observation validation is identity-bound, complete, and time-bounded',()=>{const base=spawnSync('/usr/bin/git',['-C',root,'rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim(),baseTree=spawnSync('/usr/bin/git',['-C',root,'show','-s','--format=%T',base],{encoding:'utf8'}).stdout.trim(),selector='fixture-selector',now=Date.now(),identity={dev:1,ino:2,mode:33261,uid:501,nlink:1,size:42,mtimeMs:1234},resolvedPath='/usr/bin/php',hash=s=>crypto.createHash('sha256').update(s).digest('hex'),observation={authority:'base-owned',provenance:'host-receipt',baseCommit:base,baseTree,selector,subjectDigest:hash(`${base}:${baseTree}:${selector}`),resolvedPath,identity,phpVersionId:80100,extensions:['json','hash','sodium','mysqli'],lint:'pass',fixture:'pass',observedAt:new Date(now-1000).toISOString(),expiresAt:new Date(now+899000).toISOString(),validitySeconds:900};observation.sha256=hash(`${base}:${baseTree}:${selector}:${resolvedPath}:${JSON.stringify(identity)}`);assert.equal(validatePhpObservation(observation,base,baseTree,selector,now),true);for(const mutation of [o=>o.phpVersionId=80099,o=>o.extensions=['json','hash'],o=>o.lint='fail',o=>o.fixture='fail',o=>o.identity={...o.identity,size:43},o=>o.observedAt=new Date(now+1).toISOString(),o=>o.expiresAt=new Date(now-1).toISOString(),o=>o.selector='foreign']){const changed=structuredClone(observation);mutation(changed);assert.equal(validatePhpObservation(changed,base,baseTree,selector,now),false)}});
test('starter capsule omits stale current branch and embedded doc-sync authority',()=>{const starter=fs.readFileSync(path.join(root,'scripts/worktree-task-start.sh'),'utf8');assert.doesNotMatch(starter,/payload\["doc_sync_(?:label|repo_id|path_prefix)"\]/);assert.match(starter,/"branch": feature_branch/);assert.match(starter,/"current": \{"head": base_sha, "tree": base_tree, "recorded_at": started_at\}/)});
